version: '3.8'
services:

  plex:
    image: linuxserver/plex:${PLEX_VERSION}
    container_name: plex
    depends_on:
      - protonvpn
    network_mode: service:protonvpn
    restart: unless-stopped
    # devices:
    #   - /dev/dri:/dev/dri # Intel QuickSync acceleration ON - Uncomment if your machine is capable
    env_file:
      - ${CONFIG_FOLDER}/plex/.env
    environment:
      PGID: ${GID}
      PUID: ${UID}
      UMASK: ${UMASK}
      TZ: ${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/plex/config:/config:Z
      - ${CONFIG_FOLDER}/plex/transcode:/transcode:Z
      - ${MEDIA_FOLDER}/Series:/data/Series:z
      - ${MEDIA_FOLDER}/Movies:/data/Movies:z
      - ${MEDIA_FOLDER}/Music:/data/Music:z

  protonvpn:
    image: ghcr.io/tprasadtp/protonvpn:${PROTONVPN_VERSION}
    container_name: protonvpn
    network_mode: bridge
    restart: unless-stopped
    env_file:
      - ${CONFIG_FOLDER}/protonvpn/.env
      - .env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5076:5076 # nzbhydra2-http or nzbhydra2-https
      - 6789:6789 # nzbget-http
      - 6791:6791 # nzbget-https
      - 6868:6868 # lidarr-https / readarr-https
      - 7878:7878 # radarr-http
      - 8082:8082 # qbittorrent
      - 8191:8191 # flaresolverr-http
      - 8686:8686 # lidarr-http
      - 8989:8989 # sonarr-http
      - 9117:9117 # jackett-http
      - 9898:9898 # sonarr-https / radarr-https
      - 32400:32400 # plex
      - 1900:1900/udp # plex
      - 3005:3005 # plex
      #- 5353:5353/udp # plex
      - 8324:8324 # plex
      - 32410:32410/udp # plex
      - 32412:32412/udp # plex
      - 32413:32413/udp # plex
      - 32414:32414/udp # plex
      - 32469:32469 # plex

  flaresolverr:
    image: flaresolverr/flaresolverr:${FLARESOLVER_VERSION}
    container_name: flaresolverr
    depends_on:
      - protonvpn
    network_mode: service:protonvpn
    restart: unless-stopped
    env_file:
      - ${CONFIG_FOLDER}/flaresolverr/.env
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/jackett/config:/config:Z

  jackett:
    image: linuxserver/jackett:${JACKETT_VERSION}
    container_name: jackett
    depends_on:
      - protonvpn
      - flaresolverr
    network_mode: service:protonvpn
    restart: unless-stopped
    env_file:
      - ${CONFIG_FOLDER}/jackett/.env
    environment:
      PGID: ${GID}
      PUID: ${UID}
      UMASK: ${UMASK}
      TZ: ${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/jackett/config:/config:Z
      - ${TORRENT_BLACKHOLE_FOLDER}:/blackhole:z

  nzbhydra2:
    image: linuxserver/nzbhydra2:${NZBHYDRA2_VERSION}
    container_name: nzbhydra2
    depends_on:
      - protonvpn
      - jackett
    network_mode: service:protonvpn
    restart: unless-stopped
    env_file:
      - ${CONFIG_FOLDER}/nzbhydra2/.env
    environment:
      PUID: ${UID}
      PGID: ${GID}
      UMASK: ${UMASK}
      TZ: ${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/nzbhydra2/config:/config:Z
      - ${TORRENT_BLACKHOLE_FOLDER}:/downloads/torrent/blackhole:z
      - ${USENET_BLACKHOLE_FOLDER}:/downloads/usenet/blackhole:z 

  qbittorrent:
    image: linuxserver/qbittorrent:${QBITTORRENT_VERSION}
    container_name: qbittorrent
    depends_on:
      - protonvpn
    network_mode: service:protonvpn
    restart: unless-stopped
    env_file:
      - ${CONFIG_FOLDER}/qbittorrent/.env
    environment:
      PUID: ${UID}
      PGID: ${GID}
      UMASK: ${UMASK}
      TZ: ${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/qbittorrent/config:/config:z
      - ${TORRENT_BLACKHOLE_FOLDER}:/blackhole:z
      - ${TORRENT_DOWNLOADS_FOLDER}:/downloads:z
      - ${MEDIA_FOLDER}/AudioBooks:/audiobooks:z
      - ${MEDIA_FOLDER}/eBooks:/books:z
      - ${MEDIA_FOLDER}/Movies:/movies:z
      - ${MEDIA_FOLDER}/Music:/music:z
      - ${MEDIA_FOLDER}/Series:/tv:z

  nzbget:
    image: linuxserver/nzbget:${NZBGET_VERSION}
    container_name: nzbget
    depends_on:
      - protonvpn
    network_mode: service:protonvpn
    restart: unless-stopped
    env_file:
      - ${CONFIG_FOLDER}/nzbget/.env
    environment:
      PUID: ${UID}
      PGID: ${GID}
      UMASK: ${UMASK}
      TZ: ${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/nzbget/config:/config:Z
      - ${USENET_BLACKHOLE_FOLDER}:/blackhole:z
      - ${USENET_DOWNLOADS_FOLDER}:/downloads:z
      - ${MEDIA_FOLDER}/AudioBooks:/audiobooks:z
      - ${MEDIA_FOLDER}/Comics:/comics:z
      - ${MEDIA_FOLDER}/eBooks:/ebooks:z
      - ${MEDIA_FOLDER}/Movies:/movies:z
      - ${MEDIA_FOLDER}/Music:/music:z
      - ${MEDIA_FOLDER}/Series:/series:z

  sonarr:
    image: linuxserver/sonarr:${SONARR_VERSION}
    container_name: sonarr
    depends_on:
      - plex
      - protonvpn
      - qbittorrent
      - nzbget
      - nzbhydra2
    network_mode: service:protonvpn
    restart: unless-stopped
    env_file:
      - ${CONFIG_FOLDER}/sonarr/.env
    environment:
      PUID: ${UID}
      PGID: ${GID}
      TZ: ${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/sonarr/config:/config:Z
      - ${RECYCLE_FOLDER}/sonarr:/recycle:z
      - ${TORRENT_DOWNLOADS_FOLDER}/completed/Sonarr:/downloads/completed/Sonarr:z
      - ${TORRENT_DOWNLOADS_FOLDER}:/downloads/torrent:z
      - ${USENET_DOWNLOADS_FOLDER}:/downloads/usenet:z
      - ${USENET_DOWNLOADS_FOLDER}/completed/Series:/downloads/completed/Series:z
      - ${MEDIA_FOLDER}/Series:/series:z
  
  radarr:
    image: linuxserver/radarr:${RADARR_VERSION}
    container_name: radarr
    depends_on:
      - plex
      - protonvpn
      - qbittorrent
      - nzbget
      - nzbhydra2
    network_mode: service:protonvpn
    restart: unless-stopped
    env_file:
      - ${CONFIG_FOLDER}/radarr/.env
    environment:
      PUID: ${UID}
      PGID: ${GID}
      UMASK: ${UMASK}
      TZ: ${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/radarr/config:/config:Z
      - ${RECYCLE_FOLDER}/radarr:/recycle:z
      - ${TORRENT_DOWNLOADS_FOLDER}:/downloads/torrent:z
      - ${TORRENT_DOWNLOADS_FOLDER}/completed/Radarr:/downloads/completed/Radarr:z
      - ${USENET_DOWNLOADS_FOLDER}:/downloads/usenet:z
      - ${USENET_DOWNLOADS_FOLDER}/completed/Movies:/downloads/completed/Movies:z
      - ${MEDIA_FOLDER}/Movies:/movies:z

  lidarr:
    image: linuxserver/lidarr:${LIDARR_VERSION}
    container_name: lidarr
    depends_on:
      - plex
      - protonvpn
      - qbittorrent
      - nzbget
      - nzbhydra2
    network_mode: service:protonvpn
    restart: unless-stopped
    env_file:
      - ${CONFIG_FOLDER}/lidarr/.env
    environment:
      PUID: ${UID}
      PGID: ${GID}
      UMASK: ${UMASK}
      TZ: ${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_FOLDER}/lidarr/config:/config:Z
      - ${RECYCLE_FOLDER}/lidarr:/recycle:z
      - ${TORRENT_DOWNLOADS_FOLDER}:/downloads/torrent:z
      - ${TORRENT_DOWNLOADS_FOLDER}/completed/Lidarr:/downloads/completed/Lidarr:z
      - ${USENET_DOWNLOADS_FOLDER}:/downloads/usenet:z
      - ${USENET_DOWNLOADS_FOLDER}/completed/Music:/downloads/completed/Music:z
      - ${MEDIA_FOLDER}/Music:/music:z
